version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Allow Dependabot to update direct and indirect dependencies in requirements.txt
    # (set to "direct" if you prefer restricting to direct dependencies only)
    allow:
      - dependency-type: "all"
